services:
  mongo:
    image: mongo:7
    command: [ --replSet, chartreuse-replicaset, --bind_ip_all ]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chartreuse-shop
    healthcheck:
      test: >
        echo "try { rs.status() } catch(err) { rs.initiate({ _id : 'chartreuse-replicaset' , members : [ { _id : 0 , host: 'mongo:27017' } ]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      start_period: 10s

  rabbitmq-broker:
    image: rabbitmq:3.9.8-management
    #    container_name: ${RABBITMQ_HOST}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VIRTUAL_HOST}
    mem_reservation: 200M
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - chartreuse-shop
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_alarms" ]

  monitoring-grafana:
    image: grafana/grafana-oss:9.3.2
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/default.yaml:ro
    networks:
      - chartreuse-shop

  monitoring-tempo:
    image: grafana/tempo:1.5.0
    command: --config.file=/etc/tempo/config.yml
    volumes:
      - ./config/tempo.yml:/etc/tempo/config.yml:ro
    networks:
      - chartreuse-shop

  monitoring-prometheus:
    image: bitnami/prometheus:2.41.0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - chartreuse-shop

  monitoring-otel-collector:
    image: otel/opentelemetry-collector-contrib:0.69.0
    command: [ "--config=/etc/otel-collector/config.yml" ]
    ports:
      - "4318:4318"
    volumes:
      - ./config/otel-collector.yml:/etc/otel-collector/config.yml
    networks:
      - chartreuse-shop

volumes:
  mongo-data:
  rabbitmq-data:
networks:
  chartreuse-shop:

