apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    version: 1
    uid: tempo
    editable: true
    url: http://monitoring-tempo:3100
    isDefault: false
    basicAuth: false
    apiVersion: 1
    jsonData: {}
